### ISSUE TITLE
no classes? sounds like a c ripoff

### ISSUE THREAD

**Issue by firefish111** [cursorweb/Europa-Lang#1]

**Comment by cursorweb** [comment]
It can't be a rip off if its better

**Comment by justamirror** [comment]
Besides, this barely even started to exist, you can judge it yet.

**Comment by firefish111** [comment]
@cursorweb can't argue with that

**Comment by darkdarcool** [comment]
No you can not

**Comment by Get-DevVed-YT** [comment]
> It can't be a rip off if its better

So... it's a ripoff then.

**Comment by cursorweb** [comment]
dyn c

**Comment by firefish111** [comment]
> > It can't be a rip off if its better
> 
> So... it's a ripoff then.
> (EDIT: I'm kidding lmao)

shut up
